name: gitlab-ci

on: [ pull_request, workflow_dispatch ]

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Gitlab CI
        uses: pulp-platform/pulp-actions/gitlab-ci@v2.5.1 # update version as needed, not autoupdated
        # Skip on forks or pull requests from forks due to missing secrets.
        if: github.repository == 'rfiorani/TestCI' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: compute.eees.dei.unibo.it:8929
          repo: rfiorani/test-ci-runner
          token: ${{ secrets.GITLAB_TOKEN }}
